import {mkdir,writeFile,readFile,copyFile,access,rm,rename,mkdtemp} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
// Accepts https://host, wss://host/ws or just host, and returns the WebSocket address the game connects to.
export function toSocketUrl(input){
 const text=String(input??'').trim();if(!text)return null;
 let url;try{url=new URL(/^[a-z]+:\/\//i.test(text)?text:`wss://${text}`);}catch{throw new Error(`Invalid server address: ${text}`);}
 if(url.protocol==='https:')url.protocol='wss:';else if(url.protocol==='http:')url.protocol='ws:';
 if(!['ws:','wss:'].includes(url.protocol))throw new Error(`Server address must be http(s) or ws(s): ${text}`);
 if(url.pathname==='/'||url.pathname==='')url.pathname='/ws';
 return url.toString();
}
// The matchmaking server baked into builds: KADKATON_SERVER_URL, else kadkaton.config.json, else none.
export async function configuredServerUrl(){
 if(process.env.KADKATON_SERVER_URL)return toSocketUrl(process.env.KADKATON_SERVER_URL);
 try{return toSocketUrl(JSON.parse(await readFile(path.join(root,'kadkaton.config.json'),'utf8')).serverUrl);}catch(error){if(error.code==='ENOENT')return null;throw error;}
}
export async function build(variant,{serverUrl,dist:distRoot}={}){
 if(!['debug','game','generation'].includes(variant))throw new Error('Build variant must be debug, game or generation.');
 const baked=serverUrl===undefined?await configuredServerUrl():toSocketUrl(serverUrl),dist=distRoot??path.join(root,'dist'),output=path.join(dist,variant);await mkdir(dist,{recursive:true});
 try{await access(output);await access(path.join(output,'.kadkaton-build'));}catch(error){
  try{await access(output);throw new Error(`Refusing to replace unmanaged build directory: ${output}`);}catch(missing){if(missing.code!=='ENOENT')throw missing;}
 }
 const staging=await mkdtemp(path.join(dist,`.${variant}-`));
 try{
  await mkdir(path.join(staging,'src/scenes'),{recursive:true});await mkdir(path.join(staging,'src/net'),{recursive:true});
  await mkdir(path.join(staging,'src/art'),{recursive:true});
  for(const file of ['index.html','style.css','src/main.js','src/battle-royale.js','src/feedback.js','src/audio.js','src/music.js','src/elements.js','src/art/characters.js','src/art/lobby.js','src/art/forest.js','src/art/biomes.js','src/art/enemies.js','src/simulation.js','src/balance.js','src/rng.js','src/wands.js','src/items.js','src/enemies.js','src/spells.js','src/puzzles.js','src/renderer.js','src/generator.js','src/locations.js','src/scenes/lobby.js','src/net/config.js','src/net/codec.js','src/net/snapshot.js','src/net/host.js','src/net/client.js','src/net/matchmaking.js','src/net/rtc.js'])await copyFile(path.join(root,file),path.join(staging,file));
  await writeFile(path.join(staging,'src/net/config.js'),`// Generated by the build.\nexport const SERVER_URL=${JSON.stringify(baked)};\n`);
  const scene=variant==='debug'?'debug':variant==='generation'?'generation':'lobby';
  await copyFile(path.join(root,`src/scenes/${scene}.js`),path.join(staging,`src/scenes/${scene}.js`));
  await writeFile(path.join(staging,'src/scene.js'),`export {createScene} from './scenes/${scene}.js';\n`);
  await writeFile(path.join(staging,'.kadkaton-build'),variant+'\n');
  await writeFile(path.join(staging,'build-info.json'),JSON.stringify({variant,scene,serverUrl:baked},null,2)+'\n');
  // The managed marker was checked above; no unrelated files are removed.
  await rm(output,{recursive:true,force:true});await rename(staging,output);
 }catch(error){await rm(staging,{recursive:true,force:true});throw error;}
 return output;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const variant=process.argv[2]||'all';for(const target of variant==='all'?['debug','game','generation']:[variant])console.log(`Built ${target}: ${await build(target)}`);
}
