import {CONFIG} from './simulation.js';
// All primitive artwork is isolated here; gameplay never reads drawing assets.
export function render(ctx,s,width,height){const scale=height/CONFIG.worldHeight*CONFIG.cameraZoom;const visibleWidth=width/scale,visibleHeight=height/scale;const cameraX=visibleWidth>=CONFIG.worldWidth?(CONFIG.worldWidth-visibleWidth)/2:Math.max(0,Math.min(CONFIG.worldWidth-visibleWidth,s.player.x-visibleWidth/2));const cameraY=(CONFIG.worldHeight-visibleHeight)/2;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#161e27';ctx.fillRect(0,0,width,height);ctx.setTransform(scale,0,0,scale,-cameraX*scale,-cameraY*scale);ctx.fillStyle='#202a32';ctx.fillRect(0,0,CONFIG.worldWidth,CONFIG.worldHeight);ctx.strokeStyle='#31404a';ctx.lineWidth=1;for(let x=0;x<=CONFIG.worldWidth;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,CONFIG.worldHeight);ctx.stroke();}for(let y=0;y<=CONFIG.worldHeight;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(CONFIG.worldWidth,y);ctx.stroke();}ctx.strokeStyle='#6a8290';ctx.lineWidth=8;ctx.strokeRect(4,4,CONFIG.worldWidth-8,CONFIG.worldHeight-8);
for(const t of s.targets){ctx.fillStyle='#8e6372';ctx.fillRect(t.x-22,t.y-22,44,44);ctx.strokeStyle='#e8b4c4';ctx.lineWidth=3;ctx.strokeRect(t.x-12,t.y-12,24,24);ctx.fillStyle='#d9e3ec';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText(`Hits: ${t.hits} · Damage: ${t.damage}`,t.x,t.y+44);}
for(const i of s.items){ctx.strokeStyle='#ffcf7760';ctx.lineWidth=2;ctx.beginPath();ctx.arc(i.x,i.y,26,0,Math.PI*2);ctx.stroke();wand(ctx,i.x,i.y,-.5);}
const p=s.player;drawCharacter(ctx,p);ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.fillText(p.name,p.x,p.y+40);if(p.charge){ctx.strokeStyle='#ffb34b';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,27,-Math.PI/2,-Math.PI/2+Math.PI*2*p.charge);ctx.stroke();}
for(const b of s.projectiles){ctx.fillStyle='#ff7638';ctx.beginPath();ctx.arc(b.x,b.y,b.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffe8a4';ctx.beginPath();ctx.arc(b.x,b.y,b.radius*.5,0,Math.PI*2);ctx.fill();}for(const e of s.effects){const alpha=e.life/e.duration;const radius=e.kind==='fireWave'?e.radius*(1-alpha*.65):e.radius*(1-alpha*.5);if(e.kind==='fireWave'){ctx.fillStyle=`rgba(255,100,30,${alpha*.3})`;ctx.beginPath();ctx.arc(e.x,e.y,radius,0,Math.PI*2);ctx.fill();}ctx.strokeStyle=`rgba(255,169,71,${alpha})`;ctx.lineWidth=e.kind==='fireWave'?8:4;ctx.beginPath();ctx.arc(e.x,e.y,radius,0,Math.PI*2);ctx.stroke();}}

function wand(ctx,x,y,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.strokeStyle='#d8b97e';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-12,0);ctx.lineTo(16,0);ctx.stroke();ctx.fillStyle='#ffac52';ctx.beginPath();ctx.arc(16,0,5,0,Math.PI*2);ctx.fill();ctx.restore();}

export function drawCharacter(ctx,p){ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e5ebf6';ctx.beginPath();ctx.moveTo(p.x+Math.cos(p.angle)*24,p.y+Math.sin(p.angle)*24);ctx.lineTo(p.x+Math.cos(p.angle+2)*12,p.y+Math.sin(p.angle+2)*12);ctx.lineTo(p.x+Math.cos(p.angle-2)*12,p.y+Math.sin(p.angle-2)*12);ctx.fill();if(p.wand)wand(ctx,p.x+Math.cos(p.angle+.8)*23,p.y+Math.sin(p.angle+.8)*23,p.angle);}
export function renderPreview(ctx,color){
 ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,160,110);
 ctx.save();ctx.translate(80,60);ctx.scale(1.3,1.3);
 drawCharacter(ctx,{x:0,y:0,angle:-Math.PI/2,color,wand:true});ctx.restore();
}
